services:
  splunk:
    image: splunk/splunk:9.0.4
    hostname: splunk
    container_name: splunk
    environment:
      SPLUNK_START_ARGS: "--accept-license --no-prompt"
      SPLUNK_HEC_TOKEN: "xyz789"
      SPLUNK_PASSWORD: "abcd1234"
    ports:
      - "8000:8000" # GUI
      - "8088:8088" # HTTP Event Collector (HEC)
      - "8089:8089" # REST API
    volumes:
      # - "./splunk_config/default.yml:/tmp/defaults/default.yml"
      - "./splunk_data:/opt/splunk/var"
    healthcheck:
      test: ["CMD-SHELL", "curl -k https://localhost:8088/services/collector/event -H 'Authorization: Splunk xyz789' -d '{\"event\": \"hello\"}' | grep '\"text\":\"Success\"' || exit 1"]
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 30s
